### PR TITLE
Embedded Types

### PR DESCRIPTION
**Pull request by SimonRichardson**
The following commit is in part a revert from an earlier commit.
In order to gain access to fields from embedded structs we need
to expand them correctly. To also be backwards compatible with the
previous commit, we also show the embedded nature of that struct.

Eventually we should turn that later off, but considering we've
begun actively developing using this for pylibjuju we should
remain as backwards compatible as possible.

### CODE REVIEW

**Review by manadart — APPROVED** [review]
As we discussed, this logic is congruent with how Go is encoding/decoding embedded structs; so this all looks good.

**Comment by SimonRichardson** [comment]
!!build!!

**Review by manadart — APPROVED** [review]

**Review by manadart — APPROVED** [review]

**Comment by SimonRichardson** [comment]
https://trello.com/c/yXcdOt3o/1680-cmr-jsonschema-expose-embedded-structs

**Comment by SimonRichardson** [comment]
!!build!!

**Comment by SimonRichardson** [comment]
!!build!!

**Comment by SimonRichardson** [comment]
!!build!!

**Comment by SimonRichardson** [comment]
$$merge$$

**Pull request merged**
